# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1

loader_version=0.16.14

# Mod Properties
mod_version=1.0.1
maven_group=com.vexsoftware.votifier.fabric
archives_base_name=nuvotifier-fabric


# Dependencies
fabric_version=0.116.1+1.21.1
fabric_permissions_version=0.3.1